# Build
source:       html
destination:  dist

# Encoding
encoding: utf-8

# Server
port:     4000
host:     127.0.0.1
baseurl:  ""
url:      ""

# Permalinks
permalink:  pretty

# Site settings
title: Breadboard Circuits
tagline: An HTML5 schematic editor for the web.
description: Breadboard Circuits is an HTML5 schematic editor for the web.
author: Cătălin Dogaru
